<<<<<<< HEAD
# config/packages/knp_paginator.yaml
knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
=======
knp_paginator:
    page_range: 5        
    default_options:
        page_name: page  
        sort_field_name: sort
        sort_direction_name: direction
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig' 
>>>>>>> bb9e0a621a23b9b2737377207fb1c79dfd141d1f
