knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true  # Kept from your version
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig' # Your friend's version
        # sliding_pagination: '@KnpPaginator/Pagination/sliding.html.twig' # Your version (optional if you want both)
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # Kept from your version
